import {replenishmentShortage} from './catalogue.mjs';
import {attendanceView,payrollPreview,todayIST,validMonth} from './attendance.mjs';
import {uid,now,digest,hashPassword,checkPassword} from './store.mjs';
export class AppError extends Error{constructor(message,status=422){super(message);this.status=status;}}
export const ensure=(ok,message,status=422)=>{if(!ok)throw new AppError(message,status);};
export const CENTRES=['Putty & Papering','Sealer & Papering','Grains','Spray Paint'];
export const ROLES=['MD','GM','Sales','Finance','Stock','Production','Cutting','Finishing Supervisor','Finishing','Acrylic','QC','Dispatch'];
export const RIGHTS={
 MD:['*'],GM:['overview','attendance','sales','customers','stock','production','tasks','finishing','quality','dispatch','employees','reports','audit','purchasing','manageEmployees','assign','approvePurchase'],
 Sales:['overview','attendance','sales','customers','stock','tasks','writeSales'],Finance:['overview','attendance','sales','customers','stock','finance','reports','purchasing','writeFinance'],
 Stock:['overview','attendance','sales','stock','production','dispatch','purchasing','writeStock'],Production:['overview','attendance','production','tasks','quality','stock','plan','assign','inspect'],
 Cutting:['overview','attendance','tasks'], 'Finishing Supervisor':['overview','attendance','tasks','finishing','production','assign','assignTables'],Finishing:['overview','attendance','tasks','finishing'],Acrylic:['overview','attendance','tasks'],
 QC:['overview','attendance','quality','production','inspect'],Dispatch:['overview','attendance','dispatch','dispatchGoods']};
export function can(u,p){return u?.active&&(RIGHTS[u.role]?.includes('*')||RIGHTS[u.role]?.includes(p)||u.grants?.includes(p));}
export const publicUser=u=>{const {passwordHash,emergencyContact,...rest}=u;return rest;};
const clean=(v,label,max=500)=>{ensure(typeof v==='string'&&v.trim().length>0&&v.length<=max,label+' is required.');return v.trim();};
const qty=(v,zero=false)=>{const n=Number(v);ensure(Number.isInteger(n)&&n>=(zero?0:1)&&n<=1000000,'Enter a valid whole quantity.');return n;};
const amount=v=>{ensure(/^\d+(\.\d{1,2})?$/.test(String(v)),'Enter an amount with up to two decimal places.');const [a,b='']=String(v).split('.');const n=Number(a)*100+Number(b.padEnd(2,'0'));ensure(Number.isSafeInteger(n)&&n<1e12,'Amount is too large.');return n;};
const overtimeMinutes=v=>{const n=Number(v||0);ensure(Number.isFinite(n)&&n>=0&&n<=24&&Number.isInteger(n*4),'Overtime must be in 15-minute steps from 0 to 24 hours.');return Math.round(n*60);};
const validDate=v=>{ensure(/^\d{4}-\d{2}-\d{2}$/.test(v||'')&&new Date(v).toISOString().slice(0,10)===v,'Enter a valid date.');return v;};
const normalizedPhone=v=>{const raw=String(v||'').replace(/[\s()-]/g,'');const p=raw.startsWith('+')?raw:raw.length===10?'+91'+raw:'+'+raw;ensure(/^\+[1-9]\d{7,14}$/.test(p),'Enter a valid mobile number.');return p;};
const get=(s,k,id)=>{const row=s.get(k,id);ensure(row,'Record not found.',404);return row;};
const nextNumber=(s,k,prefix)=>prefix+String(s.db.prepare('SELECT count(*) AS n FROM records WHERE kind=?').get(k).n+1).padStart(6,'0');
const requireRight=(u,p)=>ensure(can(u,p),'Your role cannot perform this action.',403);
const dateToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());
export function totals(lines,interstate=false){let subtotal=0,tax=0;const rows=lines.map(l=>{const base=l.unitPrice*l.quantity-(l.discount||0);ensure(base>=0&&Number.isSafeInteger(base),'Invalid line amount.');const cgst=interstate?0:Math.round(base*l.taxBps/20000);const sgst=cgst;const igst=interstate?Math.round(base*l.taxBps/10000):0;subtotal+=base;tax+=cgst+sgst+igst;return {...l,subtotal:base,cgst,sgst,igst,tax:cgst+sgst+igst};});return {lines:rows,subtotal,tax,total:subtotal+tax};}
export function notify(s,title,target,href,orderId){s.put('notifications',{id:uid(),title,...target,href,orderId:orderId||null,readBy:[]});}
function post(s,u,reference,description,lines,date=dateToday()){ensure(lines.every(l=>Number.isSafeInteger(l.debit)&&Number.isSafeInteger(l.credit)&&l.debit>=0&&l.credit>=0),'Invalid journal amounts.');ensure(lines.reduce((v,l)=>v+l.debit-l.credit,0)===0,'Journal is not balanced.');const setting=get(s,'settings','company');ensure(!setting.closedThrough||date>setting.closedThrough,'This accounting period is closed.');ensure(!s.list('journals').some(j=>j.reference===reference),'This financial entry already exists.',409);return s.put('journals',{id:uid(),reference,description,lines,date,actorId:u.id});}
const jline=(account,debit=0,credit=0)=>({account,debit,credit});
function move(s,u,p,kind,q,reference){ensure(p.onHand>=0&&p.reserved>=0&&p.reserved<=p.onHand,'Stock cannot become negative or fall below reservations.',409);s.put('movements',{id:uid(),productId:p.id,kind,quantity:q,onHandAfter:p.onHand,reference,actorId:u.id});s.put('products',p);}
function stageRole(stage){return stage==='Cutting'?'Cutting':stage==='Acrylic'?'Acrylic':'Finishing';}
function assignable(s,stage,id){const e=get(s,'employees',id);ensure(e.active&&e.role===stageRole(stage),'Choose an active employee from the correct work section.');return e;}
function scopedTask(u,t){if(u.role==='Finishing Supervisor')ensure(CENTRES.includes(t.stage),'You can manage only Finishing tasks.',403);}
const actionRights={businessTargets:'settings',attendanceAdjust:'manageEmployees',compensation:'manageEmployees',payrollCalculate:'manageEmployees',deleteProduct:'writeStock',staffProfile:'manageEmployees',financeReview:'writeFinance',customer:'writeSales',lead:'writeSales',order:'writeSales',reviseOrder:'writeSales',cancelOrder:'writeSales',product:'writeStock',opening:'writeStock',adjust:'writeStock',payment:'writeFinance',refund:'writeFinance',release:'writeFinance',reserve:'writeStock',requestProduction:'writeStock',plan:'plan',assignTask:'assign',verifyTask:'assign',inspect:'inspect',receiveProduction:'writeStock',pack:'writeStock',invoice:'writeFinance',clear:'writeFinance',dispatch:'dispatchGoods',assignment:'assignTables',expense:'writeFinance',purchase:'purchasing',approvePurchase:'approvePurchase',receivePurchase:'writeStock',paySupplier:'writeFinance',creditNote:'writeFinance',returnGoods:'writeStock',settings:'settings',employee:'manageEmployees',periodClose:'writeFinance',importResolve:'writeStock'};
export function command(s,u,action,b,key){
 ensure(typeof key==='string'&&key.length>=16&&key.length<=100,'A request identifier is required.');
 if(actionRights[action]){if(action==='dispatch'&&can(u,'writeStock')){}else if(action==='assignment'&&u.role==='GM'){}else if(action==='product'&&can(u,'writeFinance')){}else requireRight(u,actionRights[action]);}
 else ensure(['attendanceMark','taskAction','profile','password','readNotification'].includes(action),'Unknown action.',404);
 return s.transaction(()=>{
  const hash=digest(JSON.stringify({action,b}));const cached=s.db.prepare('SELECT * FROM receipts WHERE actor=? AND key=?').get(u.id,key);if(cached){ensure(cached.hash===hash,'Request key was reused with different content.',409);return JSON.parse(cached.result);}
  // The store tracks only rows changed by this transaction.
  let result,kind,entityId=b.id,orderId;
  function save(k,row){kind=k;result=s.put(k,row);entityId=result.id;return result;}
  function version(row){if(b.version!==undefined)ensure(Number(b.version)===row.version,'Someone updated this record. Refresh before editing.',409);}
  switch(action){
   case 'customer':{const old=b.id?get(s,'customers',b.id):{};version(old);if(old.id&&u.role==='Sales')ensure(old.ownerId===u.id,'This customer belongs to another sales employee.',403);save('customers',customerRecord(s,u,b,old));break;}
   case 'lead':{const old=b.id?get(s,'leads',b.id):{};version(old);if(old.id&&u.role==='Sales')ensure(old.ownerId===u.id,'This lead belongs to another sales employee.',403);if(b.newCustomer)b.customerId=s.put('customers',customerRecord(s,u,b.newCustomer)).id;get(s,'customers',b.customerId);ensure(['NEW','CONTACTED','QUOTED','WON','LOST'].includes(b.status||'NEW'),'Invalid lead status.');save('leads',{...old,id:b.id||uid(),customerId:b.customerId,requirement:clean(b.requirement,'Requirement',3000),followUp:validDate(b.followUp),source:b.source||'Enquiry',status:b.status||'NEW',ownerId:old.ownerId||u.id,value:amount(b.value||0),notes:b.notes||'',lines:Array.isArray(b.lines)?b.lines.slice(0,50):old.lines||[]});break;}
   case 'order': case 'reviseOrder':{const old=action==='reviseOrder'?get(s,'orders',b.id):null;version(old||{});if(old){ensure(old.status==='CONFIRMED'&&!s.list('invoices').some(i=>i.orderId===old.id),'Only unreleased, uninvoiced orders can be revised.');if(u.role==='Sales')ensure(old.ownerId===u.id,'You can revise only your own order.',403);clean(b.reason,'Revision reason');}if(b.newCustomer)b.customerId=s.put('customers',customerRecord(s,u,b.newCustomer)).id;const lead=b.leadId?get(s,'leads',b.leadId):null;if(lead){ensure(!lead.orderId,'This lead already has an order.',409);ensure(lead.ownerId===u.id||u.role==='MD','This lead belongs to another employee.',403);b.customerId=lead.customerId;}const customer=get(s,'customers',b.customerId);ensure(Array.isArray(b.lines)&&b.lines.length>0&&b.lines.length<=50,'Add 1–50 order lines.');const rows=b.lines.map(l=>{const p=l.type==='CUSTOM'?s.put('products',{id:uid(),sku:'CUSTOM-'+uid().slice(0,8).toUpperCase(),name:clean(l.specification,'Custom specification',3000),category:'Custom',productType:'CUSTOM',uom:'NOS',onHand:0,reserved:0,minimum:0,price:0,cost:0,taxBps:0,verified:true,active:true,art:'custom'}):get(s,'products',l.productId);ensure(p.active,'Product is inactive.');const custom=p.category==='Custom';ensure(!l.discount||amount(l.discount)===0,'Discounts require an approved pricing policy.');const unitPrice=custom?amount(l.price):p.price;ensure(unitPrice>0,'Price must be set before ordering.');return {id:uid(),productId:p.id,description:p.name,quantity:qty(l.quantity),unitPrice,taxBps:p.taxBps,discount:amount(l.discount||0),reserved:0,packed:0,dispatched:0,incoming:0,specification:custom?clean(l.specification,'Custom specification',3000):l.specification||''};});const calc=totals(rows,customer.state!=='Kerala');const customTotal=calc.lines.filter(l=>get(s,'products',l.productId).category==='Custom').reduce((n,l)=>n+l.subtotal+l.tax,0);const advance=Math.max(amount(b.advanceRequired||0),customTotal);ensure(advance>0&&advance<=calc.total,'Advance must be positive and no greater than the order total.');ensure(!old||old.paid<=calc.total,'Refund excess payment before reducing this order.');save('orders',{...old,id:old?.id||uid(),number:old?.number||nextNumber(s,'orders','SO-'),customerId:customer.id,ownerId:old?.ownerId||u.id,dueDate:validDate(b.dueDate),priority:b.priority||'Normal',notes:b.notes||'',status:'CONFIRMED',...calc,advanceRequired:advance,paid:old?.paid||0,pricingApproved:!customTotal,leadId:b.leadId||old?.leadId||null,clearanceVersion:null});if(lead)s.put('leads',{...lead,status:'WON',orderId:result.id});orderId=result.id;notify(s,result.number+' needs advance verification',{role:'Finance'},'finance',orderId);break;}
   case 'product':{const old=b.id?get(s,'products',b.id):{};version(old);ensure(!old.id||old.category==='Custom'===(b.category==='Custom'),'A product cannot switch between catalogue and custom.');const sku=clean(b.sku,'Product code',70);ensure(!s.list('products').some(p=>p.sku===sku&&p.id!==b.id),'This code already exists.');const taxBps=Math.round(Number(b.tax||0)*100);ensure([0,500,1200,1800,2800].includes(taxBps),'Choose a configured tax rate.');save('products',{...old,id:b.id||uid(),sku,name:clean(b.name,'Product name'),category:b.category||'Catalogue',uom:b.uom||'NOS',hsn:b.hsn||'',price:can(u,'writeFinance')?amount(b.price||0):(old.price||0),cost:can(u,'writeFinance')?amount(b.cost||0):(old.cost||0),minimum:b.minimum===''||b.minimum==null?null:qty(b.minimum,true),taxBps:can(u,'writeFinance')?taxBps:(old.taxBps||0),bin:b.bin||'',onHand:old.id?old.onHand:null,reserved:old.reserved||0,verified:old.verified||false,active:b.active!==false,art:b.art||old.art||'frame'});break;}
   case 'opening': case 'adjust':{const p=get(s,'products',b.id);version(p);clean(b.reason,'Count / adjustment reason');const count=qty(b.quantity,true);ensure(count>=p.reserved,'Count cannot be below reserved stock.');if(action==='opening')ensure(!p.verified,'Opening stock is already verified.');else ensure(['MD','GM'].includes(u.role),'A manager must approve stock adjustments.',403);const diff=count-(p.verified?p.onHand:0);p.onHand=count;p.verified=true;p.countStatus='VERIFIED';move(s,u,p,action==='opening'?'OPENING':'ADJUSTMENT',diff,key);if(diff&&p.cost)post(s,u,'STOCK-'+key,b.reason,diff>0?[jline('Inventory',diff*p.cost),jline(action==='opening'?'Opening equity':'Inventory variance',0,diff*p.cost)]:[jline('Inventory variance',-diff*p.cost),jline('Inventory',0,-diff*p.cost)]);kind='products';result=get(s,kind,p.id);break;}
   case 'payment':{const o=get(s,'orders',b.id);ensure(!['CANCELLED','RETURNED'].includes(o.status),'This order cannot receive payment.');const value=amount(b.amount);ensure(value>0&&value<=o.total-o.paid,'Payment must be positive and within the outstanding balance.');const reference=clean(b.reference,'Bank / payment reference');ensure(!s.list('payments').some(p=>p.reference===reference&&p.status==='POSTED'),'Payment reference already exists.',409);ensure(['Bank','Cash','UPI','Card'].includes(b.method),'Choose a payment method.');const pay=save('payments',{id:uid(),number:nextNumber(s,'payments','RC-'),orderId:o.id,amount:value,method:b.method,reference,status:'POSTED',actorId:u.id});o.paid+=value;o.clearanceVersion=null;s.put('orders',o);const invoiced=s.list('invoices').some(i=>i.orderId===o.id);post(s,u,'PAY-'+pay.id,'Customer receipt '+o.number,[jline(b.method==='Cash'?'Cash':'Bank',value),jline(invoiced?'Receivables':'Customer advances',0,value)]);orderId=o.id;notify(s,'Payment received for '+o.number,{role:'Sales'},'sales',o.id);break;}
   case 'refund':{const o=get(s,'orders',b.id);ensure(o.status==='CONFIRMED','Cancel fulfilment or use a credit note for invoiced orders.');const value=amount(b.amount);ensure(value>0&&value<=o.paid,'Refund exceeds received payment.');clean(b.reason,'Refund reason');save('refunds',{id:uid(),orderId:o.id,amount:value,reference:clean(b.reference,'Refund reference'),reason:b.reason,actorId:u.id});o.paid-=value;o.clearanceVersion=null;s.put('orders',o);post(s,u,'REFUND-'+result.id,b.reason,[jline('Customer advances',value),jline('Bank',0,value)]);orderId=o.id;break;}
   case 'release':{const o=get(s,'orders',b.id);ensure(o.status==='CONFIRMED','Order is already released.');ensure(o.pricingApproved!==false,'Finance must approve custom pricing before release.');ensure(o.paid>=o.advanceRequired,'The required advance has not been received.');o.status='FULFILLING';o.releasedAt=now();save('orders',o);orderId=o.id;notify(s,o.number+' released to Stock',{role:'Stock'},'stock',o.id);break;}
   case 'reserve':{const o=get(s,'orders',b.id);ensure(o.status==='FULFILLING','Finance must release this order before allocation.');let allocated=0;for(const l of o.lines){const p=get(s,'products',l.productId);if(!p.verified||p.category==='Custom')continue;const n=Math.min(l.quantity-l.reserved-l.incoming,p.onHand-p.reserved);if(n>0){l.reserved+=n;p.reserved+=n;s.put('products',p);allocated+=n;}}ensure(allocated>0,'No available stock for uncovered demand. Create a production request.');save('orders',o);orderId=o.id;break;}
   case 'requestProduction':{let o,l;const count=qty(b.quantity);let productId=b.productId;if(b.orderId){o=get(s,'orders',b.orderId);ensure(o.status==='FULFILLING','Order must be released to Stock.');l=o.lines.find(l=>l.id===b.lineId);ensure(l,'Order line not found.');ensure(count<=l.quantity-l.reserved-l.incoming,'Request exceeds uncovered demand.');productId=l.productId;l.incoming+=count;s.put('orders',o);}const p=get(s,'products',productId);ensure(p.active,'Product is inactive.');if(!o){ensure(p.category!=='Custom','Custom production must be linked to an order.');ensure(count<=replenishmentShortage(s,p),'Request exceeds verified catalogue shortage after pending production.');}else if(p.category!=='Custom'){ensure(p.verified,'Verify the stock count before requesting manufacture.');ensure(count<=Math.max(0,l.quantity-l.reserved-(l.incoming-count)-(p.onHand-p.reserved)),'Reserve available stock first; only the shortage can be produced.');}save('jobs',{id:uid(),number:nextNumber(s,'jobs','PR-'),productId:p.id,quantity:count,purpose:o?(p.category==='Custom'?'CUSTOM_ORDER':'ORDER_SHORTAGE'):'REPLENISHMENT',orderId:o?.id||null,lineId:l?.id||null,status:'REQUESTED',priority:b.priority||'Normal',dueDate:validDate(b.dueDate),specification:l?.specification||b.specification||p.name,route:[],routeIndex:0,good:0,received:0,requestedBy:u.id});orderId=o?.id;notify(s,'New request '+result.number,{role:'Production'},'production',orderId);break;}
   case 'plan':{const job=get(s,'jobs',b.id);ensure(['REQUESTED','REWORK'].includes(job.status),'This job is already planned.');const optional=Array.isArray(b.route)?b.route:[];ensure(optional.every(v=>CENTRES.includes(v)||v==='Acrylic'),'Invalid production route.');job.route=['Cutting',...CENTRES.filter(c=>optional.includes(c)),...(optional.includes('Acrylic')?['Acrylic']:[])];assignable(s,'Cutting',b.assigneeId);job.routeIndex=0;job.status='IN_PROGRESS';job.plannedAt=now();save('jobs',job);const t=s.put('tasks',{id:uid(),jobId:job.id,title:get(s,'products',job.productId).name+' · Cutting',stage:'Cutting',quantity:job.quantity,assigneeId:b.assigneeId,assignerId:u.id,status:'ASSIGNED',dueDate:job.dueDate,priority:job.priority,attempt:1});notify(s,t.title,{userId:t.assigneeId},'tasks',job.orderId);orderId=job.orderId;break;}
   case 'assignTask':{const t=get(s,'tasks',b.id);scopedTask(u,t);ensure(['UNASSIGNED','ASSIGNED','REJECTED','RECEIVED','PAUSED'].includes(t.status),'Cannot reassign active or completed work.');assignable(s,t.stage,b.assigneeId);if(t.assigneeId)clean(b.reason,'Reassignment reason');t.assigneeId=b.assigneeId;t.assignerId=u.id;t.status='ASSIGNED';t.attempt+=1;t.reason=b.reason||'';save('tasks',t);const j=get(s,'jobs',t.jobId);orderId=j.orderId;notify(s,'Assigned: '+t.title,{userId:t.assigneeId},'tasks',orderId);break;}
   case 'taskAction':{const t=get(s,'tasks',b.id);ensure(t.assigneeId===u.id,'Only the assigned employee can update their work.',403);version(t);const transitions={receive:['ASSIGNED','RECEIVED'],start:['RECEIVED','IN_PROGRESS'],resume:['PAUSED','IN_PROGRESS'],pause:['IN_PROGRESS','PAUSED'],submit:['IN_PROGRESS','SUBMITTED'],reject:['ASSIGNED','REJECTED']};const tr=transitions[b.action];ensure(tr&&t.status===tr[0],'This task is not ready for that action.',409);if(['reject','pause'].includes(b.action))t.reason=clean(b.reason,'Reason');t.status=tr[1];t[b.action+'At']=now();t.notes=b.notes||t.notes||'';save('tasks',t);orderId=get(s,'jobs',t.jobId).orderId;if(['reject','submit','pause'].includes(b.action))notify(s,t.title+' · '+tr[1].toLowerCase(),{userId:t.assignerId},'tasks',orderId);break;}
   case 'verifyTask':{const t=get(s,'tasks',b.id);scopedTask(u,t);ensure(t.status==='SUBMITTED','Employee must submit work before verification.');t.status='VERIFIED';t.verifiedAt=now();t.verifiedBy=u.id;save('tasks',t);const job=get(s,'jobs',t.jobId);job.routeIndex+=1;if(job.routeIndex>=job.route.length){job.status='AWAITING_QC';notify(s,job.number+' is ready for quality inspection',{role:'Production'},'quality',job.orderId);notify(s,job.number+' is ready for quality inspection',{role:'QC'},'quality',job.orderId);}else{const stage=job.route[job.routeIndex];s.put('tasks',{id:uid(),jobId:job.id,title:get(s,'products',job.productId).name+' · '+stage,stage,quantity:job.quantity,assigneeId:null,assignerId:u.id,status:'UNASSIGNED',dueDate:job.dueDate,priority:job.priority,attempt:0});notify(s,job.number+' needs '+stage+' assignment',{role:stage==='Acrylic'?'Production':'Finishing Supervisor'},'tasks',job.orderId);}s.put('jobs',job);orderId=job.orderId;break;}
   case 'inspect':{const job=get(s,'jobs',b.id);ensure(job.status==='AWAITING_QC','Job is not ready for QC.');const passed=qty(b.passed,true);ensure(passed<=job.quantity,'Passed quantity exceeds job quantity.');const notes=clean(b.notes,'Inspection notes');save('inspections',{id:uid(),jobId:job.id,quantity:job.quantity,passed,failed:job.quantity-passed,notes,inspectorId:u.id});job.good=passed;job.status=passed?'READY_FOR_STOCK':'REWORK_SPLIT';if(passed)job.completedAt=now();s.put('jobs',job);if(passed<job.quantity){const child=s.put('jobs',{...job,id:uid(),number:nextNumber(s,'jobs','PR-'),parentJobId:job.id,quantity:job.quantity-passed,status:'REWORK',good:0,received:0,completedAt:null,route:[],routeIndex:0,specification:job.specification+' · REWORK: '+notes});notify(s,child.number+' requires rework',{role:'Production'},'production',job.orderId);}if(passed)notify(s,job.number+' passed QC: receive '+passed,{role:'Stock'},'stock',job.orderId);orderId=job.orderId;break;}
   case 'receiveProduction':{const job=get(s,'jobs',b.id);ensure(['READY_FOR_STOCK','PART_RECEIVED'].includes(job.status),'Only QC-approved output can enter Stock.');const count=qty(b.quantity);ensure(count<=job.good-job.received,'Receipt exceeds approved unreceived quantity.');clean(b.reason,'Stock verification note');const p=get(s,'products',job.productId);ensure(p.verified,'Verify opening stock before receiving this product.');p.onHand+=count;if(job.orderId){const o=get(s,'orders',job.orderId);const l=o.lines.find(l=>l.id===job.lineId);ensure(l&&o.status==='FULFILLING','Related order is not open for fulfilment.');l.incoming-=count;l.reserved+=count;p.reserved+=count;s.put('orders',o);}move(s,u,p,'PRODUCTION_RECEIPT',count,job.number);job.received+=count;job.status=job.received===job.good?'RECEIVED':'PART_RECEIVED';job.receivedAt=now();save('jobs',job);if(p.cost)post(s,u,'PROD-'+key,'Standard-cost finished goods receipt',[jline('Inventory',p.cost*count),jline('Production clearing',0,p.cost*count)]);orderId=job.orderId;break;}
   case 'pack':{const o=get(s,'orders',b.id);ensure(o.status==='FULFILLING','Order is not in fulfilment.');ensure(o.lines.every(l=>l.reserved===l.quantity&&l.incoming===0),'Every order line must be reserved before packing.');for(const l of o.lines)l.packed=l.quantity;o.status='READY';o.packedAt=now();o.clearanceVersion=null;save('orders',o);orderId=o.id;notify(s,o.number+' is packed and ready',{role:'Finance'},'finance',o.id);notify(s,o.number+' is packed and ready',{role:'Sales'},'sales',o.id);break;}
   case 'invoice':{const o=get(s,'orders',b.id);ensure(o.status==='READY','Pack and verify goods before posting the invoice.');ensure(!s.list('invoices').some(i=>i.orderId===o.id),'Invoice already exists.',409);const company=get(s,'settings','company');ensure(company.reviewMode||company.taxVerified,'Company tax settings need verification.');save('invoices',{id:uid(),number:nextNumber(s,'invoices','INV-'),orderId:o.id,date:dateToday(),company:{name:company.name,address:company.address,gstin:company.gstin},customer:get(s,'customers',o.customerId),lines:o.lines,subtotal:o.subtotal,tax:o.tax,total:o.total,review:company.reviewMode,actorId:u.id});post(s,u,'INV-'+result.id,'Sales invoice '+result.number,[jline('Receivables',o.total),jline('Sales',0,o.subtotal),jline('Output GST',0,o.tax)]);if(o.paid)post(s,u,'ADV-'+result.id,'Apply advance to invoice',[jline('Customer advances',o.paid),jline('Receivables',0,o.paid)]);orderId=o.id;break;}
   case 'clear':{const o=get(s,'orders',b.id);ensure(o.status==='READY'&&o.paid===o.total,'Packed goods and full payment are required.');ensure(s.list('invoices').some(i=>i.orderId===o.id),'Post the invoice before clearance.');o.clearanceVersion=o.version+1;o.clearedAt=now();save('orders',o);orderId=o.id;notify(s,o.number+' financially cleared',{role:'Stock'},'dispatch',o.id);break;}
   case 'dispatch':{const o=get(s,'orders',b.id);ensure(o.status==='READY'&&o.clearanceVersion===o.version&&o.paid===o.total,'Current financial clearance and full payment are required.',409);ensure(o.lines.every(l=>l.reserved===l.quantity&&l.packed===l.quantity),'All goods must be packed.');const shipment=save('shipments',{id:uid(),number:nextNumber(s,'shipments','DN-'),orderId:o.id,carrier:clean(b.carrier,'Carrier / delivery method'),recipient:clean(b.recipient,'Recipient'),tracking:b.tracking||'',status:'DISPATCHED',actorId:u.id});let cost=0;for(const l of o.lines){const p=get(s,'products',l.productId);p.onHand-=l.quantity;p.reserved-=l.quantity;cost+=p.cost*l.quantity;move(s,u,p,'DISPATCH',-l.quantity,shipment.number);l.dispatched=l.quantity;l.reserved=0;l.packed=0;}if(cost)post(s,u,'COGS-'+shipment.id,'Cost of dispatched goods',[jline('Cost of goods sold',cost),jline('Inventory',0,cost)]);o.status='DISPATCHED';o.dispatchedAt=now();s.put('orders',o);orderId=o.id;notify(s,o.number+' dispatched to '+b.recipient,{role:'Sales'},'sales',o.id);break;}
   case 'cancelOrder':{const o=get(s,'orders',b.id);if(u.role==='Sales')ensure(o.ownerId===u.id,'You can cancel only your own orders.',403);ensure(!['DISPATCHED','CANCELLED','RETURNED'].includes(o.status),'This order cannot be cancelled.');ensure(!o.paid,'Refund received funds first.');ensure(!s.list('invoices').some(i=>i.orderId===o.id),'Posted invoices require a credit note.');ensure(o.lines.every(l=>l.incoming===0),'Resolve production requests before cancellation.');clean(b.reason,'Cancellation reason');for(const l of o.lines){const p=get(s,'products',l.productId);p.reserved-=l.reserved;s.put('products',p);l.reserved=0;l.packed=0;}o.status='CANCELLED';o.cancelReason=b.reason;o.clearanceVersion=null;save('orders',o);orderId=o.id;break;}
   case 'returnGoods':{const o=get(s,'orders',b.id);ensure(o.status==='DISPATCHED','Only dispatched goods can be returned.');const count=qty(b.quantity);const l=o.lines.find(l=>l.id===b.lineId);ensure(l&&count<=l.dispatched-(l.returned||0),'Return exceeds unreturned dispatched quantity.');const disposition=b.disposition;ensure(['RESTOCK','QUARANTINE'].includes(disposition),'Choose return disposition.');const p=get(s,'products',l.productId);if(disposition==='RESTOCK'){p.onHand+=count;move(s,u,p,'CUSTOMER_RETURN',count,o.number);if(p.cost)post(s,u,'RETURN-'+key,'Restock returned goods',[jline('Inventory',p.cost*count),jline('Cost of goods sold',0,p.cost*count)]);}l.returned=(l.returned||0)+count;s.put('orders',o);save('returns',{id:uid(),orderId:o.id,lineId:l.id,productId:p.id,quantity:count,disposition,reason:clean(b.reason,'Return reason'),credited:false,actorId:u.id});orderId=o.id;notify(s,o.number+' has a return needing credit review',{role:'Finance'},'finance',o.id);break;}
   case 'creditNote':{const r=get(s,'returns',b.id);ensure(!r.credited,'Return already credited.');const o=get(s,'orders',r.orderId),l=o.lines.find(l=>l.id===r.lineId);const subtotal=l.unitPrice*r.quantity;const calc=totals([{unitPrice:l.unitPrice,quantity:r.quantity,taxBps:l.taxBps}],get(s,'customers',o.customerId).state!=='Kerala');save('creditNotes',{id:uid(),number:nextNumber(s,'creditNotes','CN-'),returnId:r.id,orderId:o.id,subtotal,tax:calc.tax,total:calc.total,reason:clean(b.reason,'Credit reason'),actorId:u.id});post(s,u,'CN-'+result.id,b.reason,[jline('Sales returns',subtotal),jline('Output GST',calc.tax),jline('Customer refunds payable',0,calc.total)]);r.credited=true;s.put('returns',r);orderId=o.id;break;}
   case 'assignment':{const e=get(s,'employees',b.employeeId);ensure(e.active&&e.role==='Finishing','Choose a Finishing worker.');ensure(CENTRES.includes(b.centre),'Choose a valid work centre.');const date=validDate(b.date),shift=b.shift||'Day';ensure(['Day','Evening'].includes(shift),'Invalid shift.');const old=s.list('assignments').find(a=>a.employeeId===e.id&&a.date===date&&a.shift===shift);save('assignments',{id:old?.id||uid(),employeeId:e.id,centre:b.centre,date,shift,supervisorId:u.id});notify(s,'Your '+shift.toLowerCase()+' table: '+b.centre,{userId:e.id},'finishing');break;}
   case 'expense':{const value=amount(b.amount);ensure(value>0,'Expense must be positive.');ensure(['Rent','Utilities','Salaries','Transport','Office expenses','Production expenses'].includes(b.account),'Choose an expense account.');save('expenses',{id:uid(),description:clean(b.description,'Description'),account:b.account,amount:value,date:validDate(b.date),reference:clean(b.reference,'Reference'),actorId:u.id});post(s,u,'EXP-'+result.id,b.description,[jline(b.account,value),jline('Bank',0,value)],b.date);break;}
   case 'purchase':{ensure(can(u,'writeStock')||can(u,'writeFinance')||u.role==='GM','Purchasing access required.',403);get(s,'products',b.productId);save('purchases',{id:uid(),number:nextNumber(s,'purchases','PO-'),supplier:clean(b.supplier,'Supplier'),productId:b.productId,quantity:qty(b.quantity),unitCost:amount(b.unitCost),dueDate:validDate(b.dueDate),status:'PENDING_APPROVAL',received:0,paid:0,actorId:u.id});notify(s,result.number+' needs approval',{role:'GM'},'purchasing');break;}
   case 'approvePurchase':{const p=get(s,'purchases',b.id);ensure(p.status==='PENDING_APPROVAL','Purchase is already approved.');p.status='APPROVED';p.approvedBy=u.id;save('purchases',p);notify(s,p.number+' approved for receipt',{role:'Stock'},'purchasing');break;}
   case 'receivePurchase':{const po=get(s,'purchases',b.id);ensure(['APPROVED','PART_RECEIVED'].includes(po.status),'Purchase needs approval.');const count=qty(b.quantity);ensure(count<=po.quantity-po.received,'Receipt exceeds ordered quantity.');const p=get(s,'products',po.productId);ensure(p.verified,'Opening stock requires verification.');p.onHand+=count;move(s,u,p,'PURCHASE_RECEIPT',count,po.number);po.received+=count;po.status=po.received===po.quantity?'RECEIVED':'PART_RECEIVED';save('purchases',po);post(s,u,'PO-RECEIPT-'+key,'Goods received '+po.number,[jline('Inventory',po.unitCost*count),jline('Payables',0,po.unitCost*count)]);break;}
   case 'paySupplier':{const po=get(s,'purchases',b.id);const value=amount(b.amount);ensure(value>0&&value<=po.received*po.unitCost-po.paid,'Payment exceeds received goods payable.');po.paid+=value;save('purchases',po);post(s,u,'SUP-PAY-'+key,clean(b.reference,'Bank reference'),[jline('Payables',value),jline('Bank',0,value)]);break;}
   case 'attendanceMark':{ensure(u.role!=='MD','MD attendance is not recorded.',403);const date=todayIST(),id='ATT-'+u.id+'-'+date,old=s.get('attendance',id);if(!old){save('attendance',{id,employeeId:u.id,date,status:'PRESENT',checkInAt:now(),checkOutAt:null,durationMinutes:0,overtimeMinutes:0,source:'SELF'});}else{ensure(old.status==='PRESENT'&&!old.checkOutAt,'Today’s attendance is already complete.',409);const checkOutAt=now(),durationMinutes=Math.max(0,Math.round((Date.parse(checkOutAt)-Date.parse(old.checkInAt))/60000));save('attendance',{...old,checkOutAt,durationMinutes});}break;}
   case 'attendanceAdjust':{ensure(['MD','GM'].includes(u.role),'Only MD and GM can manage attendance.',403);const employee=get(s,'employees',b.employeeId);ensure(employee.role!=='MD','MD attendance is not recorded.');const date=validDate(b.date);ensure(date<=todayIST(),'Future attendance cannot be entered.');ensure(date>=employee.joined,'Attendance cannot precede the joining date.');const status=String(b.status||'');ensure(['PRESENT','HALF_DAY','PAID_LEAVE','UNPAID_LEAVE','ABSENT','HOLIDAY'].includes(status),'Choose a valid attendance status.');const id='ATT-'+employee.id+'-'+date,old=s.get('attendance',id)||{};clean(b.reason,'Attendance note');save('attendance',{...old,id,employeeId:employee.id,date,status,checkInAt:status==='PRESENT'?old.checkInAt||null:null,checkOutAt:status==='PRESENT'?old.checkOutAt||null:null,durationMinutes:status==='PRESENT'?old.durationMinutes||0:0,overtimeMinutes:overtimeMinutes(b.overtimeHours),source:'MANAGER',managerId:u.id,note:b.reason});break;}
   case 'compensation':{ensure(['MD','GM'].includes(u.role),'Only MD and GM can manage compensation.',403);const employee=get(s,'employees',b.id);ensure(employee.role!=='MD','MD is excluded from staff payroll.');version(employee);employee.monthlySalary=amount(b.monthlySalary||0);employee.overtimeRate=amount(b.overtimeRate||0);employee.compensationUpdatedAt=now();employee.compensationUpdatedBy=u.id;save('employees',employee);result=publicUser(result);break;}
   case 'payrollCalculate':{ensure(['MD','GM'].includes(u.role),'Only MD and GM can calculate payroll.',403);const month=validMonth(b.month);ensure(month<=todayIST().slice(0,7),'Future payroll cannot be calculated.');const preview=payrollPreview(s,month,b.employeeId);const id='PAYROLL-'+month+'-'+b.employeeId,old=s.get('payrolls',id);save('payrolls',{...old,...preview,id,status:'CALCULATED',calculatedBy:u.id});break;}
   case 'employee':{ensure(['MD','GM'].includes(u.role),'Only MD and GM can edit employees.',403);const old=b.id?get(s,'employees',b.id):{};version(old);ensure(b.id!==u.id,'Use your profile to change your details; another manager must change your access.');ensure(ROLES.includes(b.role),'Invalid role.');if(u.role!=='MD')ensure(!['MD','GM','Finance'].includes(b.role)&&!['MD','GM','Finance'].includes(old.role),'Only MD can manage privileged accounts.',403);ensure(old.role!=='MD','The MD account cannot be changed here.');const email=clean(b.email,'Email').toLowerCase();ensure(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Invalid email.');ensure(!s.list('employees').some(e=>e.email===email&&e.id!==b.id),'Email already in use.');let passwordHash=old.passwordHash;if(!old.id||b.password){ensure(typeof b.password==='string'&&b.password.length>=12,'Use a password of at least 12 characters.');passwordHash=hashPassword(b.password);}const grants=u.role==='MD'?(b.grants||[]):old.grants||[];ensure(grants.every(g=>Object.keys(RIGHTS).flatMap(r=>RIGHTS[r]).includes(g)&&g!=='*'),'Unknown permission grant.');const e=save('employees',{...old,id:b.id||uid(),name:clean(b.name,'Employee name'),email,role:b.role,department:b.department||b.role,title:b.title||b.role,phone:b.phone?normalizedPhone(b.phone):'',whatsapp:b.whatsapp?normalizedPhone(b.whatsapp):'',photoUrl:photoURL(b.photoUrl),joined:validDate(b.joined||dateToday()),active:b.active!==false,passwordHash,grants,skills:old.skills||[],avatarColor:old.avatarColor||'teal'});s.db.prepare('DELETE FROM sessions WHERE user_id=?').run(e.id);result=publicUser(e);break;}
   case 'profile':case 'staffProfile':{ensure(['MD','GM'].includes(u.role),'Only MD and GM can edit staff profiles.',403);const w=get(s,'employees',b.id||u.id);version(w);w.name=clean(b.name,'Name');w.title=clean(b.title,'Position');w.phone=b.phone?normalizedPhone(b.phone):'';w.whatsapp=b.whatsapp?normalizedPhone(b.whatsapp):'';w.photoUrl=photoURL(b.photoUrl);save('employees',w);result=publicUser(result);break;}
   case 'deleteProduct':{const p=get(s,'products',b.id);version(p);ensure(!p.reserved,'Release reserved stock before archiving.');ensure(!s.list('jobs').some(j=>j.productId===p.id&&!['RECEIVED','REWORK_SPLIT','CANCELLED'].includes(j.status)),'Complete production before archiving.');ensure(!s.list('orders').some(o=>!['CANCELLED','DISPATCHED'].includes(o.status)&&o.lines.some(l=>l.productId===p.id)),'This product belongs to an open order.');p.active=false;p.archivedAt=now();p.archiveReason=clean(b.reason,'Archive reason');save('products',p);break;}
   case 'financeReview':{const o=get(s,'orders',b.id);version(o);ensure(o.status==='CONFIRMED','Pricing is locked after Stock release.');ensure(Array.isArray(b.lines),'Supply line prices.');const lines=o.lines.map(l=>{if(get(s,'products',l.productId).category!=='Custom')return l;const proposed=b.lines.find(x=>x.id===l.id);ensure(proposed,'Custom price is missing.');const taxBps=Number(proposed.tax)*100;ensure([0,500,1200,1800,2800].includes(taxBps),'Choose a valid tax rate.');const unitPrice=amount(proposed.price);ensure(unitPrice>0,'Custom price must be positive.');return {...l,unitPrice,taxBps};});const calc=totals(lines,get(s,'customers',o.customerId).state!=='Kerala');ensure(o.paid<=calc.total,'Refund excess payment before reducing the order.');const customTotal=calc.lines.filter(l=>get(s,'products',l.productId).category==='Custom').reduce((n,l)=>n+l.subtotal+l.tax,0);save('orders',{...o,...calc,advanceRequired:Math.max(customTotal,Math.min(o.advanceRequired,calc.total)),pricingApproved:true,pricingApprovedBy:u.id,pricingApprovedAt:now(),clearanceVersion:null});orderId=o.id;notify(s,o.number+' pricing approved',{role:'Sales'},'sales',o.id);break;}
   case 'password':{ensure(checkPassword(String(b.currentPassword||''),u.passwordHash),'Current password is incorrect.',403);ensure(typeof b.password==='string'&&b.password.length>=12,'Use at least 12 characters.');const e=get(s,'employees',u.id);e.passwordHash=hashPassword(b.password);save('employees',e);s.db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id);result={ok:true,reauthenticate:true};break;}
   case 'settings':{ensure(u.role==='MD','Only MD can change company settings.',403);const old=get(s,'settings','company');save('settings',{...old,name:clean(b.name,'Company name'),address:b.address||'',gstin:b.gstin||'',lowStockAlerts:b.lowStockAlerts!==false});break;}
   case 'businessTargets':{ensure(u.role==='MD','Only MD can set business targets.',403);const old=get(s,'settings','company');save('settings',{...old,salesTargetDaily:amount(b.salesTargetDaily||0),salesTargetMonthly:amount(b.salesTargetMonthly||0),productionTargetDaily:amount(b.productionTargetDaily||0),productionTargetMonthly:amount(b.productionTargetMonthly||0)});break;}
   case 'periodClose':{const setting=get(s,'settings','company');const date=validDate(b.date);ensure(!setting.closedThrough||date>setting.closedThrough,'Choose a date later than the closed period.');ensure(date<=dateToday(),'Cannot close a future period.');clean(b.reason,'Period close reason');setting.closedThrough=date;save('settings',setting);break;}
   case 'importResolve':{const imp=get(s,'imports',b.id);const index=Number(b.index);ensure(Number.isInteger(index)&&imp.rows[index],'Source row not found.');const r=imp.rows[index];ensure(!r.resolved,'Source row already reviewed.');const disposition=b.disposition;ensure(['EXCLUDE','CONFIRM'].includes(disposition),'Choose a disposition.');clean(b.reason,'Review reason');if(disposition==='CONFIRM'){ensure(!imp.duplicateCodes.includes(r.code),'Duplicate codes need consolidation before approval.');ensure(r.code!=='CUSTOM','CUSTOM must become a unique product specification.');const existing=s.list('products').find(p=>p.sku===r.code);ensure(!existing?.verified,'Opening count already verified.');const p=s.put('products',{...existing,id:existing?.id||uid(),sku:r.code,name:clean(b.name,'Product description'),category:b.category||'Catalogue',uom:clean(b.uom,'Unit'),onHand:qty(b.quantity,true),reserved:0,minimum:b.minimum===''||b.minimum==null?null:qty(b.minimum,true),price:can(u,'writeFinance')?amount(b.price||0):(existing?.price||0),cost:can(u,'writeFinance')?amount(b.cost||0):(existing?.cost||0),taxBps:existing?.taxBps||0,hsn:existing?.hsn||'',verified:true,active:true,art:'frame',bin:''});move(s,u,p,'VERIFIED_IMPORT',p.onHand,imp.hash);if(p.cost&&p.onHand)post(s,u,'IMPORT-'+p.id,'Approved opening stock',[jline('Inventory',p.cost*p.onHand),jline('Opening equity',0,p.cost*p.onHand)]);}r.resolved=true;r.disposition=disposition;r.reviewedBy=u.id;r.reviewedAt=now();r.reason=b.reason;save('imports',imp);break;}
   case 'readNotification':{const n=get(s,'notifications',b.id);ensure(n.userId===u.id||n.role===u.role||['MD','GM'].includes(u.role),'This notification belongs to another employee.',403);n.readBy=[...new Set([...n.readBy,u.id])];save('notifications',n);break;}
  }
  const changes=s.changes.filter(r=>r.kind!=='notifications').map(r=>{const redact=v=>{if(!v)return null;const {passwordHash,emergencyContact,...rest}=v;return rest;};return {...r,before:redact(r.before),after:redact(r.after)};});
  s.event({actorId:u.id,actorName:u.name,action,entityKind:kind||action,entityId:entityId||u.id,orderId:orderId||(['orders'].includes(kind)?entityId:null),reason:b.reason||b.notes||'',changes,requestKey:key});
  result=result||{ok:true};s.db.prepare('INSERT INTO receipts(actor,key,hash,result) VALUES(?,?,?,?)').run(u.id,key,hash,JSON.stringify(result));return result;
 });
}
export const COLLECTION_RIGHTS={attendance:'attendance',payrolls:'employees',customers:'customers',leads:'sales',orders:'sales',products:'stock',jobs:'production',tasks:'tasks',assignments:'finishing',payments:'finance',refunds:'finance',invoices:'finance',creditNotes:'finance',journals:'reports',expenses:'finance',purchases:'purchasing',movements:'stock',shipments:'dispatch',returns:'finance',inspections:'quality',imports:'stock',audit:'audit'};
export function records(s,u,kind,supplied){
 const list=()=>supplied??s.list(kind);
 if(kind==='employees'){return list().map(e=>can(u,'employees')?publicUser(e):{id:e.id,name:e.name,role:e.role,department:e.department,active:e.active,avatarColor:e.avatarColor,title:e.title,photoUrl:e.photoUrl});}
 if(kind==='notifications')return list().filter(n=>n.userId===u.id||n.role===u.role||['MD','GM'].includes(u.role));
 if(kind==='settings')return [get(s,'settings','company')];
 const right=COLLECTION_RIGHTS[kind];if(!((kind==='customers'&&(can(u,'writeStock')||can(u,'dispatchGoods')))||(kind==='orders'&&can(u,'dispatchGoods'))))requireRight(u,right||'unknown');let rows=kind==='audit'?(supplied??s.events()):list();
 if(kind==='orders'&&u.role==='Dispatch')rows=rows.filter(o=>['READY','DISPATCHED'].includes(o.status));
 if(kind==='tasks'&&!can(u,'assign'))rows=rows.filter(t=>t.assigneeId===u.id);
 if(kind==='tasks'&&u.role==='Finishing Supervisor')rows=rows.filter(t=>CENTRES.includes(t.stage));
 if(kind==='assignments'&&u.role==='Finishing')rows=rows.filter(a=>a.employeeId===u.id);
 if(kind==='attendance'&&!['MD','GM'].includes(u.role))rows=rows.filter(a=>a.employeeId===u.id);
 if(kind==='products'&&!can(u,'reports'))rows=rows.map(({cost,...p})=>p);
 if(kind==='imports'&&!can(u,'writeStock'))rows=rows.map(({rows,...r})=>r);
 return rows;
}
export function report(s,u,from='',to='9999-12-31'){
 requireRight(u,'reports');const journalCount=s.db.prepare("SELECT count(*) AS n FROM records WHERE kind='journals' AND json_extract(data,'$.date') BETWEEN ? AND ?").get(from,to).n;const ledger=Object.fromEntries(s.db.prepare("SELECT json_extract(l.value,'$.account') AS account,sum(json_extract(l.value,'$.debit')) AS debit,sum(json_extract(l.value,'$.credit')) AS credit FROM records r,json_each(r.data,'$.lines') l WHERE r.kind='journals' AND json_extract(r.data,'$.date') BETWEEN ? AND ? GROUP BY json_extract(l.value,'$.account')").all(from,to).map(r=>[r.account,r]));
 const net=a=>(ledger[a]?.credit||0)-(ledger[a]?.debit||0);const revenue=net('Sales')+net('Sales returns');const cogs=-net('Cost of goods sold');const accounts=['Rent','Utilities','Salaries','Transport','Office expenses','Production expenses','Inventory variance'];const expenses=-accounts.reduce((v,a)=>v+net(a),0);return {from,to,revenue,cogs,grossProfit:revenue-cogs,expenses,netProfit:revenue-cogs-expenses,ledger:Object.values(ledger),journals:journalCount,productionClearing:net('Production clearing'),provisional:true};
}

function photoURL(value){if(!value)return '';ensure(typeof value==='string'&&value.length<2048,'Invalid photo URL.');let url;try{url=new URL(value);}catch{throw new AppError('Enter a valid HTTPS photo URL.');}ensure(url.protocol==='https:'&&!url.username&&!url.password,'Photo links must use HTTPS without credentials.');return url.href;}
function customerRecord(s,u,b,old={}){const phone=normalizedPhone(b.phone),whatsapp=normalizedPhone(b.whatsapp),city=clean(b.city,'Place');ensure(!s.list('customers').some(c=>c.phone===phone&&c.id!==old.id),'This mobile number already has a customer profile.',409);const dates=Array.isArray(b.specialDates)?b.specialDates:[];ensure(dates.length<=30,'Use up to 30 special dates.');return {...old,id:old.id||uid(),name:clean(b.name,'Customer name'),phone,whatsapp,city,state:b.state||'Kerala',address:String(b.address||'').slice(0,2000),email:String(b.email||'').slice(0,254),company:String(b.company||'').slice(0,200),occupation:String(b.occupation||'').slice(0,200),postcode:String(b.postcode||'').slice(0,20),country:String(b.country||'India').slice(0,80),dob:b.dob?validDate(b.dob):'',gstin:String(b.gstin||'').slice(0,20),notes:String(b.notes||'').slice(0,4000),tags:String(b.tags||'').slice(0,500),specialDates:dates.map(d=>({type:clean(d.type,'Special date type',100),label:String(d.label||'').slice(0,150),date:validDate(d.date)})),ownerId:old.ownerId||u.id};}
