import {readFileSync,existsSync} from 'node:fs';
import {digest,now} from './store.mjs';

// RFC 4180 fields, including quoted commas, quotes and newlines.
export function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV contains an unclosed quoted field.');if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
export function analyseStock(text){const rows=parseCSV(text.replace(/^\uFEFF/,''));const starts=rows[0].flatMap((v,i)=>v.trim().toUpperCase()==='ITEM CODE'?[i]:[]);if(starts.length!==4)throw Error('Expected the four catalogue blocks.');const items=[];const number=v=>{if(!String(v??'').trim())return null;const n=Number(v);if(!Number.isInteger(n)||n<0)throw Error('Invalid source quantity: '+v);return n;};rows.slice(1).forEach((row,i)=>starts.forEach((start,b)=>{const code=row[start]?.trim();if(code)items.push({row:i+2,block:b+1,code,quantity:number(row[start+1]),minimum:number(row[start+2])});}));const codes=[...new Set(items.map(r=>r.code))];return {sha256:digest(text),items,duplicateCodes:codes.filter(c=>items.filter(r=>r.code===c).length>1),itemCount:items.length,uniqueCodes:codes.length,physicalRows:rows.length,missingQuantities:items.filter(r=>r.quantity===null).length};}
export function importCatalogue(s,text){const src=analyseStock(text);if(s.list('products').length)throw Error('Initial catalogue import requires an empty product master.');s.transaction(()=>{for(const code of new Set(src.items.map(r=>r.code))){if(code==='CUSTOM')continue;const rows=src.items.filter(r=>r.code===code),duplicate=rows.length>1,r=rows[0];s.put('products',{id:'CAT-'+code,sku:code,name:code,category:'Catalogue',productType:'CATALOGUE',uom:'',price:0,cost:0,taxBps:0,hsn:'',minimum:duplicate?null:r.minimum,onHand:duplicate?null:r.quantity,reserved:0,verified:false,countStatus:duplicate?'CONFLICT':r.quantity===null?'UNKNOWN':'SOURCE',sourceRows:rows,pricingVerified:false,active:true,art:'catalogue',bin:''});}s.put('imports',{id:'stock-source',name:'Factory 1 stock catalogue',hash:src.sha256,status:'NEEDS_RECONCILIATION',rows:src.items,duplicateCodes:src.duplicateCodes,itemCount:src.itemCount,uniqueCodes:src.uniqueCodes,missingQuantities:src.missingQuantities,physicalRows:src.physicalRows});s.event({actorId:'system',actorName:'Catalogue import',action:'catalogue_import',entityKind:'imports',entityId:'stock-source',sourceHash:src.sha256,codeCount:src.uniqueCodes-1});});return src;}
export function initialiseClean(s){if(!s.get('settings','company'))s.put('settings',{id:'company',name:'Hanicraft Creative LLP',address:'',currency:'INR',timezone:'Asia/Kolkata',gstin:'',taxVerified:false,reviewMode:true,closedThrough:'',lowStockAlerts:true});}
export function stockCapacity(s){const products=s.list('products').filter(p=>p.active&&p.category!=='Custom'),jobs=s.list('jobs').filter(j=>!['RECEIVED','REWORK_SPLIT','CANCELLED'].includes(j.status));const unknown=products.filter(p=>!p.verified||!Number.isInteger(p.minimum)||!Number.isInteger(p.onHand));const shortages=products.filter(p=>Number.isInteger(p.onHand)&&Number.isInteger(p.minimum)&&p.onHand-p.reserved<p.minimum);const customDemand=s.list('orders').some(o=>!['CANCELLED','DISPATCHED'].includes(o.status)&&o.lines.some(l=>s.get('products',l.productId)?.category==='Custom'&&l.dispatched<l.quantity));return {catalogueCount:products.length,unknownCount:unknown.length,shortageCount:shortages.length,activeProduction:jobs.length,customDemand,salesFocus:products.length>0&&!unknown.length&&!shortages.length&&!jobs.length&&!customDemand};}
export function replenishmentShortage(s,p){if(!p.active||p.category==='Custom'||!p.verified||!Number.isInteger(p.minimum)||!Number.isInteger(p.onHand))return 0;const incoming=s.list('jobs').filter(j=>j.productId===p.id&&j.purpose==='REPLENISHMENT'&&!['RECEIVED','REWORK_SPLIT','CANCELLED'].includes(j.status)).reduce((n,j)=>n+(j.status==='READY_FOR_STOCK'||j.status==='PART_RECEIVED'?j.good-j.received:j.quantity-j.received),0);return Math.max(0,p.minimum-(p.onHand-p.reserved)-incoming);}
