import {can,ensure,CENTRES} from './business.mjs';
const todayIST=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());
const shiftDate=(date,days)=>{const value=new Date(date+'T00:00:00Z');value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10);};
const percentage=(actual,target)=>target?Math.round(actual/target*100):null;
export function executiveMetrics(s){
 const today=todayIST(),month=today.slice(0,7),dayNumber=Number(today.slice(8)),[year,monthNumber]=month.split('-').map(Number),daysInMonth=new Date(Date.UTC(year,monthNumber,0)).getUTCDate(),start=shiftDate(today,-6),settings=s.get('settings','company')||{};
 const grouped=(sql,...args)=>Object.fromEntries(s.db.prepare(sql).all(...args).map(row=>[row.day,row.value||0]));
 const orderDaily=grouped("SELECT date(json_extract(data,'$.createdAt'),'+5 hours','+30 minutes') AS day,sum(json_extract(data,'$.total')) AS value FROM records WHERE kind='orders' AND json_extract(data,'$.status')!='CANCELLED' AND date(json_extract(data,'$.createdAt'),'+5 hours','+30 minutes') BETWEEN ? AND ? GROUP BY day",start,today);
 const paymentDaily=grouped("SELECT date(json_extract(data,'$.createdAt'),'+5 hours','+30 minutes') AS day,sum(json_extract(data,'$.amount')) AS value FROM records WHERE kind='payments' AND json_extract(data,'$.status')='POSTED' AND date(json_extract(data,'$.createdAt'),'+5 hours','+30 minutes') BETWEEN ? AND ? GROUP BY day",start,today);
 const productionDaily=grouped("SELECT date(COALESCE(json_extract(j.data,'$.completedAt'),json_extract(j.data,'$.receivedAt')),'+5 hours','+30 minutes') AS day,sum(COALESCE(json_extract(j.data,'$.good'),0)*COALESCE(json_extract(p.data,'$.price'),0)) AS value FROM records j JOIN records p ON p.kind='products' AND p.id=json_extract(j.data,'$.productId') WHERE j.kind='jobs' AND COALESCE(json_extract(j.data,'$.completedAt'),json_extract(j.data,'$.receivedAt')) IS NOT NULL AND date(COALESCE(json_extract(j.data,'$.completedAt'),json_extract(j.data,'$.receivedAt')),'+5 hours','+30 minutes') BETWEEN ? AND ? GROUP BY day",start,today);
 const scalar=(sql,...args)=>s.db.prepare(sql).get(...args).value||0;
 const totalSales=scalar("SELECT sum(json_extract(data,'$.total')) AS value FROM records WHERE kind='orders' AND json_extract(data,'$.status')!='CANCELLED'");
 const received=scalar("SELECT sum(json_extract(data,'$.amount')) AS value FROM records WHERE kind='payments' AND json_extract(data,'$.status')='POSTED'");
 const pending=scalar("SELECT sum(json_extract(data,'$.total')-json_extract(data,'$.paid')) AS value FROM records WHERE kind='orders' AND json_extract(data,'$.status')!='CANCELLED'");
 const revenue=scalar("SELECT sum(CASE WHEN json_extract(l.value,'$.account') IN ('Sales','Sales returns') THEN json_extract(l.value,'$.credit')-json_extract(l.value,'$.debit') ELSE 0 END) AS value FROM records r,json_each(r.data,'$.lines') l WHERE r.kind='journals'");
 const monthSales=scalar("SELECT sum(json_extract(data,'$.total')) AS value FROM records WHERE kind='orders' AND json_extract(data,'$.status')!='CANCELLED' AND date(json_extract(data,'$.createdAt'),'+5 hours','+30 minutes') LIKE ?",month+'%');
 const monthReceived=scalar("SELECT sum(json_extract(data,'$.amount')) AS value FROM records WHERE kind='payments' AND json_extract(data,'$.status')='POSTED' AND date(json_extract(data,'$.createdAt'),'+5 hours','+30 minutes') LIKE ?",month+'%');
 const monthProduction=scalar("SELECT sum(COALESCE(json_extract(j.data,'$.good'),0)*COALESCE(json_extract(p.data,'$.price'),0)) AS value FROM records j JOIN records p ON p.kind='products' AND p.id=json_extract(j.data,'$.productId') WHERE j.kind='jobs' AND COALESCE(json_extract(j.data,'$.completedAt'),json_extract(j.data,'$.receivedAt')) IS NOT NULL AND date(COALESCE(json_extract(j.data,'$.completedAt'),json_extract(j.data,'$.receivedAt')),'+5 hours','+30 minutes') LIKE ?",month+'%');
 const targets={salesDaily:settings.salesTargetDaily||0,salesMonthly:settings.salesTargetMonthly||0,productionDaily:settings.productionTargetDaily||0,productionMonthly:settings.productionTargetMonthly||0};
 const todaySales=orderDaily[today]||0,todayProduction=productionDaily[today]||0,salesMonthlyPct=percentage(monthSales,targets.salesMonthly),productionMonthlyPct=percentage(monthProduction,targets.productionMonthly),collectionRate=totalSales?Math.round(received/totalSales*100):0;
 const healthInputs=[salesMonthlyPct,productionMonthlyPct,collectionRate].filter(value=>value!==null),healthScore=healthInputs.length?Math.max(0,Math.min(100,Math.round(healthInputs.reduce((sum,value)=>sum+Math.min(100,value),0)/healthInputs.length))):0;
 const trends=Array.from({length:7},(_,index)=>{const date=shiftDate(start,index);return {date,sales:orderDaily[date]||0,production:productionDaily[date]||0,received:paymentDaily[date]||0};});
 return {today,month,daysInMonth,elapsedDays:dayNumber,targets,totalSales,revenue,received,pending,collectionRate,todaySales,todayProduction,monthSales,monthProduction,monthReceived,salesDailyPct:percentage(todaySales,targets.salesDaily),productionDailyPct:percentage(todayProduction,targets.productionDaily),salesMonthlyPct,productionMonthlyPct,projectedSales:dayNumber?Math.round(monthSales/dayNumber*daysInMonth):0,projectedProduction:dayNumber?Math.round(monthProduction/dayNumber*daysInMonth):0,healthScore,healthStatus:!Object.values(targets).some(Boolean)?'TARGETS_NOT_SET':healthScore>=80?'HEALTHY':healthScore>=50?'WATCH':'NEEDS_ATTENTION',trends};
}
export function metrics(s,u){
 const group=kind=>Object.fromEntries(s.db.prepare("SELECT json_extract(data,'$.status') AS status,count(*) AS n FROM records WHERE kind=? GROUP BY json_extract(data,'$.status')").all(kind).map(r=>[r.status,r.n]));
 const orders=can(u,'sales')||can(u,'reports')?group('orders'):{};
 const jobs=can(u,'production')||can(u,'reports')?group('jobs'):{};
 const scalar=(sql,...args)=>s.db.prepare(sql).get(...args).n||0;
 const financial=can(u,'sales')||can(u,'writeFinance')||can(u,'reports');
 return {orders,jobs,outstanding:financial?scalar("SELECT sum(json_extract(data,'$.total')-json_extract(data,'$.paid')) AS n FROM records WHERE kind='orders' AND json_extract(data,'$.status')!='CANCELLED'"):0,receipts:can(u,'writeFinance')||can(u,'reports')?scalar("SELECT sum(json_extract(data,'$.amount')) AS n FROM records WHERE kind='payments' AND json_extract(data,'$.status')='POSTED'"):0,lateOrders:financial?scalar("SELECT count(*) AS n FROM records WHERE kind='orders' AND json_extract(data,'$.status') NOT IN ('DISPATCHED','CANCELLED') AND json_extract(data,'$.dueDate')<?",todayIST()):0,inventoryValue:can(u,'reports')?scalar("SELECT sum(COALESCE(json_extract(data,'$.onHand'),0)*COALESCE(json_extract(data,'$.cost'),0)) AS n FROM records WHERE kind='products'"):0,rework:can(u,'production')||can(u,'reports')?scalar("SELECT count(*) AS n FROM records WHERE kind='jobs' AND json_extract(data,'$.parentJobId') IS NOT NULL"):0,executive:u.role==='MD'?executiveMetrics(s):null};
}
export function operations(s,u){ensure(can(u,'reports'),'Management reporting access is required.',403);const rows=(kind,where)=>s.db.prepare("SELECT data FROM records WHERE kind=? AND ("+where+") ORDER BY json_extract(data,'$.createdAt') DESC,id DESC LIMIT 50").all(kind).map(r=>JSON.parse(r.data));const products=rows('products',"json_extract(data,'$.verified')=1 AND json_extract(data,'$.onHand')-json_extract(data,'$.reserved')<json_extract(data,'$.minimum')");const orders=rows('orders',"json_extract(data,'$.total')>json_extract(data,'$.paid') AND json_extract(data,'$.status')!='CANCELLED'");const workload=s.db.prepare("SELECT json_extract(data,'$.assigneeId') AS employeeId,sum(CASE WHEN json_extract(data,'$.status')='VERIFIED' THEN 1 ELSE 0 END) AS verified,sum(CASE WHEN json_extract(data,'$.status')!='VERIFIED' THEN 1 ELSE 0 END) AS open FROM records WHERE kind='tasks' AND json_extract(data,'$.assigneeId') IS NOT NULL GROUP BY json_extract(data,'$.assigneeId') ORDER BY open DESC LIMIT 50").all().map(w=>({...w,name:s.get('employees',w.employeeId)?.name||'',role:s.get('employees',w.employeeId)?.role||''}));return {products,orders:orders.map(o=>({...o,customerName:s.get('customers',o.customerId)?.name||''})),workload,metrics:metrics(s,u),limit:50};}
