import {hashPassword,uid,now} from './store.mjs';
import {readFileSync,existsSync} from 'node:fs';
export const REVIEW_PASSWORD='HaniLocal!2026';
export function seed(s,sourcePath){if(s.list('employees').length)return;
 s.transaction(()=>{
 const roles=[['md','Managing Director','MD'],['gm','General Manager','GM'],['sales','Sales Executive','Sales'],['finance','Finance Officer','Finance'],['stock','Stock Coordinator','Stock'],['production','Production Manager','Production'],['cnc','CNC Operator','Cutting'],['laser','Laser Operator','Cutting'],['stationary','Stationary Operator','Cutting'],['supervisor','Finishing Supervisor','Finishing Supervisor'],...Array.from({length:11},(_,i)=>['finishing'+(i+1),'Finishing Artisan '+String(i+1).padStart(2,'0'),'Finishing']),['acrylic1','Acrylic Artisan 01','Acrylic'],['acrylic2','Acrylic Artisan 02','Acrylic']];
 for(const [login,name,role] of roles)s.put('employees',{id:login,name,role,email:login+'@hanicraft.local',passwordHash:hashPassword(REVIEW_PASSWORD),active:true,department:role==='MD'||role==='GM'?'Management':role.startsWith('Finishing')?'Finishing':role,phone:'',title:name,joined:'2026-09-01',skills:role==='Cutting'?[login.toUpperCase()]:[],emergencyContact:'',grants:[],avatarColor:['teal','purple','blue','orange'][roles.findIndex(r=>r[0]===login)%4]});
 s.put('settings',{id:'company',name:'Hanicraft Creative LLP',address:'Company address pending verification',currency:'INR',timezone:'Asia/Kolkata',gstin:'',taxVerified:false,reviewMode:true,closedThrough:'',lowStockAlerts:true});
 const products=[['HC-101','Classic wall frame','Frames',64000,28000,34,12,'frame'],['HC-204','Arch desk keepsake','Keepsakes',48000,19000,18,15,'arch'],['HC-308','Botanical name board','Name boards',125000,52000,6,10,'leaf'],['HC-412','Circle celebration plaque','Plaques',89000,36000,12,8,'circle'],['HC-502','Heritage wooden trophy','Trophies',156000,72000,4,8,'trophy'],['HC-CUSTOM','Bespoke creative piece','Custom',180000,75000,0,0,'custom']];
 for(const [sku,name,category,price,cost,onHand,minimum,art]of products)s.put('products',{id:sku,sku,name,category,price,cost,onHand,reserved:0,minimum,uom:'NOS',taxBps:500,hsn:'8306',verified:true,art,active:true,bin:'A-'+(products.findIndex(x=>x[0]===sku)+1),reviewData:true});
 const customers=[['c1','Aster Interiors','+919000000101','Kochi'],['c2','Mira Design Studio','+919000000102','Kozhikode'],['c3','The Willow Collective','+919000000103','Thrissur'],['c4','Olive & Oak','+919000000104','Kannur']];
 for(const [id,name,phone,city]of customers)s.put('customers',{id,name,phone,city,state:'Kerala',address:city,email:'',gstin:'',ownerId:'sales',notes:'Fictional review customer',reviewData:true});
 s.put('leads',{id:'lead1',customerId:'c4',requirement:'Welcome plaques for a boutique opening',source:'Instagram',status:'NEW',ownerId:'sales',followUp:'2026-09-18',value:4200000});
 s.put('leads',{id:'lead2',customerId:'c2',requirement:'Custom festive gifting collection',source:'Referral',status:'CONTACTED',ownerId:'sales',followUp:'2026-09-19',value:8600000});
 const orders=[['o1','HC-260901','c1','HC-101',12,'CONFIRMED',300000],['o2','HC-260902','c2','HC-308',8,'FULFILLING',500000],['o3','HC-260903','c3','HC-204',6,'FULFILLING',150000]];
 for(const [id,number,customerId,productId,quantity,status,paid]of orders){const p=s.get('products',productId);const subtotal=p.price*quantity,cgst=Math.round(subtotal*.025),total=subtotal+cgst*2;const order=s.put('orders',{id,number,customerId,ownerId:'sales',dueDate:id==='o2'?'2026-09-18':'2026-09-22',priority:id==='o2'?'Urgent':'Normal',status,subtotal,tax:cgst*2,total,paid,advanceRequired:paid,clearanceVersion:null,notes:'Fictional order for local review',lines:[{id:uid(),productId,description:p.name,quantity,unitPrice:p.price,taxBps:500,subtotal,cgst,sgst:cgst,tax:cgst*2,reserved:0,packed:0,dispatched:0,incoming:0,specification:''}]});s.put('payments',{id:'pay-'+id,orderId:id,number:'RC-'+number,amount:paid,method:'Bank',reference:'REVIEW-'+id,status:'POSTED',actorId:'finance'});s.put('journals',{id:'j-'+id,reference:'REVIEW-'+id,description:'Review customer advance',date:'2026-09-16',lines:[{account:'Bank',debit:paid,credit:0},{account:'Customer advances',debit:0,credit:paid}]});s.event({actorId:'sales',actorName:'Sales Executive',action:'Order confirmed',entityKind:'orders',entityId:id,orderId:id,after:order,reviewData:true});}
 s.put('jobs',{id:'job1',number:'PR-260901',productId:'HC-502',quantity:12,purpose:'REPLENISHMENT',orderId:null,lineId:null,status:'REQUESTED',priority:'High',dueDate:'2026-09-21',specification:'Catalogue finish • natural walnut',route:[],good:0,received:0,requestedBy:'stock'});
 s.put('jobs',{id:'job2',number:'PR-260902',productId:'HC-412',quantity:10,purpose:'REPLENISHMENT',orderId:null,lineId:null,status:'IN_PROGRESS',priority:'Normal',dueDate:'2026-09-20',specification:'Satin gold edge, standard engraving',route:['Cutting','Putty & Papering','Spray Paint'],routeIndex:0,good:0,received:0,requestedBy:'stock'});
 s.put('tasks',{id:'task1',jobId:'job2',title:'Circle celebration plaque · Cutting',stage:'Cutting',quantity:10,assigneeId:'cnc',assignerId:'production',status:'ASSIGNED',dueDate:'2026-09-20',priority:'Normal',attempt:1,notes:''});
 const centres=['Putty & Papering','Sealer & Papering','Grains','Spray Paint'];for(let i=1;i<=11;i++)s.put('assignments',{id:'a'+i,employeeId:'finishing'+i,centre:centres[(i-1)%4],date:'2026-09-16',shift:'Day',supervisorId:'supervisor'});
 for(const [role,title,href] of [['Stock','Two orders are ready for allocation','stock'],['Production','New replenishment request: PR-260901','production'],['Finance','Advance received · review HC-260901','finance']])s.put('notifications',{id:uid(),role,title,href,readBy:[],actorId:'system'});
 s.put('notifications',{id:uid(),userId:'cnc',title:'Your cutting assignment is ready to receive',href:'tasks',readBy:[],actorId:'production'});
 if(sourcePath&&existsSync(sourcePath)){const src=JSON.parse(readFileSync(sourcePath,'utf8'));const rows=src.items||src.entries||[];s.put('imports',{id:'stock-source',name:'FACTORY 1 STOCK — original CSV',hash:src.sha256,status:'NEEDS_RECONCILIATION',rows,physicalRows:111,itemCount:199,uniqueCodes:197,missingQuantities:64,duplicateCodes:['NMH413B','NMH428'],notes:'BALENCE is quantity minus minimum; it is not available stock.'});}
 for(const p of s.list('products'))if(p.onHand){s.put('movements',{id:uid(),productId:p.id,kind:'REVIEW_OPENING',quantity:p.onHand,onHandAfter:p.onHand,reference:'Review opening',actorId:'system'});s.put('journals',{id:uid(),reference:'OPEN-'+p.id,description:'Review opening inventory',date:'2026-09-16',lines:[{account:'Inventory',debit:p.onHand*p.cost,credit:0},{account:'Opening equity',debit:0,credit:p.onHand*p.cost}]});}
 });
}
