import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {openStore} from '../local/store.mjs';
import {seed,REVIEW_PASSWORD} from '../local/seed.mjs';
import {command,records,totals,report} from '../local/business.mjs';
import {createApp} from '../local/server.mjs';
import {mkdtempSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const setup=()=>{const s=openStore(':memory:');seed(s);return s;};
const run=(s,user,action,data={},key=randomUUID())=>command(s,s.get('employees',user),action,data,key);
function newOrder(s,productId='HC-101',quantity=2){return run(s,'sales','order',{customerId:'c1',dueDate:'2026-10-01',advanceRequired:'100',lines:[{productId,quantity,specification:'Blue lettering',price:'1200'}]});}
function pay(s,id,amount){return run(s,'finance','payment',{id,amount,method:'Bank',reference:randomUUID()});}
function finish(s,jobId,route=[]){run(s,'production','plan',{id:jobId,assigneeId:'cnc',route});for(;;){const j=s.get('jobs',jobId);if(j.status==='AWAITING_QC')break;const t=s.list('tasks').find(t=>t.jobId===jobId&&t.status!=='VERIFIED');let manager='production';if(t.status==='UNASSIGNED'){const employee=t.stage==='Acrylic'?'acrylic1':'finishing1';manager=t.stage==='Acrylic'?'production':'supervisor';run(s,manager,'assignTask',{id:t.id,assigneeId:employee});}const current=s.get('tasks',t.id);for(const a of ['receive','start','submit'])run(s,current.assigneeId,'taskAction',{id:t.id,action:a});run(s,manager,'verifyTask',{id:t.id});}}
test('GST split rounding matches the supplied bill: 3 × 57.14 = 180.00',()=>{const t=totals([{unitPrice:5714,quantity:3,taxBps:500}]);assert.equal(t.subtotal,17142);assert.equal(t.tax,858);assert.equal(t.total,18000);assert.equal(t.lines[0].cgst,429);assert.equal(t.lines[0].sgst,429);});
test('23 individual accounts, 11 Finishing workers and one supervisor',()=>{const s=setup();assert.equal(s.list('employees').length,23);assert.equal(s.list('employees').filter(e=>e.role==='Finishing').length,11);assert.equal(s.list('employees').filter(e=>e.role==='Finishing Supervisor').length,1);s.close();});
test('available stock order → advance → reserve → pack → invoice → full payment → clearance → dispatch',()=>{const s=setup();const o=newOrder(s);const p=s.get('products','HC-101');assert.throws(()=>run(s,'stock','reserve',{id:o.id}),/release/);assert.throws(()=>run(s,'finance','release',{id:o.id}),/advance/);pay(s,o.id,'100');run(s,'finance','release',{id:o.id});run(s,'stock','reserve',{id:o.id});assert.equal(s.get('products',p.id).onHand,p.onHand);assert.equal(s.get('products',p.id).reserved,2);run(s,'stock','pack',{id:o.id});assert.throws(()=>run(s,'finance','clear',{id:o.id}),/full payment/);run(s,'finance','invoice',{id:o.id});pay(s,o.id,((o.total-10000)/100).toFixed(2));run(s,'finance','clear',{id:o.id});const key=randomUUID();const a=run(s,'stock','dispatch',{id:o.id,carrier:'Collection',recipient:'Test recipient'},key);const b=run(s,'stock','dispatch',{id:o.id,carrier:'Collection',recipient:'Test recipient'},key);assert.equal(a.id,b.id);assert.equal(s.get('products',p.id).onHand,p.onHand-2);assert.equal(s.get('products',p.id).reserved,0);assert.equal(s.get('orders',o.id).status,'DISPATCHED');assert.throws(()=>run(s,'stock','dispatch',{id:o.id,carrier:'Collection',recipient:'Again'}),/clearance/);const r=report(s,s.get('employees','md'));assert.equal(r.ledger.reduce((v,l)=>v+l.debit-l.credit,0),0);assert.equal(r.revenue,o.subtotal);assert.equal(r.cogs,p.cost*2);assert.ok(s.events().filter(e=>e.orderId===o.id).length>=8);s.close();});
test('custom production → all finishing stages → optional Acrylic → partial QC → rework → stock receipt',()=>{const s=setup();const o=newOrder(s,'HC-CUSTOM',4);run(s,'finance','financeReview',{id:o.id,lines:o.lines.map(l=>({id:l.id,price:'1200',tax:'5'}))});pay(s,o.id,'5040');run(s,'finance','release',{id:o.id});const l=s.get('orders',o.id).lines[0];const j=run(s,'stock','requestProduction',{orderId:o.id,lineId:l.id,quantity:4,dueDate:'2026-10-01'});assert.throws(()=>run(s,'stock','requestProduction',{orderId:o.id,lineId:l.id,quantity:1,dueDate:'2026-10-01'}),/uncovered/);assert.throws(()=>run(s,'stock','receiveProduction',{id:j.id,quantity:4,reason:'too early'}),/QC/);finish(s,j.id,['Putty & Papering','Sealer & Papering','Grains','Spray Paint','Acrylic']);run(s,'production','inspect',{id:j.id,passed:3,notes:'One scratch needs rework'});run(s,'stock','receiveProduction',{id:j.id,quantity:3,reason:'Counted and verified'});const child=s.list('jobs').find(x=>x.parentJobId===j.id);assert.equal(child.quantity,1);finish(s,child.id);run(s,'production','inspect',{id:child.id,passed:1,notes:'Passed after rework'});run(s,'stock','receiveProduction',{id:child.id,quantity:1,reason:'Verified'});const order=s.get('orders',o.id);assert.equal(order.lines[0].reserved,4);assert.equal(order.lines[0].incoming,0);run(s,'stock','pack',{id:o.id});assert.equal(s.get('orders',o.id).status,'READY');assert.ok(s.list('notifications').some(n=>n.userId==='acrylic1'));s.close();});
test('replenishment covers a verified shortage, including while some stock is available',()=>{const s=setup();const product=s.get('products','HC-101');product.minimum=40;s.put('products',product);const before=product.onHand;const j=run(s,'stock','requestProduction',{productId:'HC-101',quantity:3,dueDate:'2026-10-01'});assert.equal(j.purpose,'REPLENISHMENT');finish(s,j.id);run(s,'production','inspect',{id:j.id,passed:3,notes:'Pass'});run(s,'stock','receiveProduction',{id:j.id,quantity:3,reason:'Stock count'});assert.equal(s.get('products','HC-101').onHand,before+3);s.close();});
test('server rejects cross-role actions and employee impersonation',()=>{const s=setup();for(const id of ['sales','stock','cnc','finishing1','acrylic1'])assert.throws(()=>run(s,id,'payment',{id:'o1',amount:'1',method:'Cash',reference:randomUUID()}),e=>e.status===403);assert.throws(()=>run(s,'md','taskAction',{id:'task1',action:'receive'}),e=>e.status===403);assert.throws(()=>records(s,s.get('employees','finishing1'),'journals'),e=>e.status===403);assert.throws(()=>records(s,s.get('employees','sales'),'audit'),e=>e.status===403);assert.equal(records(s,s.get('employees','finishing1'),'tasks').length,0);assert.ok(records(s,s.get('employees','stock'),'products').every(p=>!('cost'in p)));s.close();});
test('reject with reason notifies assigning manager; reassignment retains history',()=>{const s=setup();assert.throws(()=>run(s,'cnc','taskAction',{id:'task1',action:'reject'}),/Reason/);run(s,'cnc','taskAction',{id:'task1',action:'reject',reason:'Machine maintenance'});assert.ok(s.list('notifications').some(n=>n.userId==='production'&&n.title.includes('rejected')));assert.throws(()=>run(s,'production','assignTask',{id:'task1',assigneeId:'finishing1',reason:'Move'}),/correct work section/);run(s,'production','assignTask',{id:'task1',assigneeId:'laser',reason:'Use available machine'});assert.equal(s.get('tasks','task1').attempt,2);assert.throws(()=>run(s,'cnc','taskAction',{id:'task1',action:'receive'}),e=>e.status===403);assert.ok(s.events().some(e=>e.action==='assignTask'&&e.changes[0].before.assigneeId==='cnc'));s.close();});
test('optimistic revisions and idempotency reject conflicting writes',()=>{const s=setup();const c=s.get('customers','c1');run(s,'sales','customer',{...c,whatsapp:c.phone,name:'Updated',version:c.version});assert.throws(()=>run(s,'sales','customer',{...c,whatsapp:c.phone,name:'Stale',version:c.version}),e=>e.status===409);const key=randomUUID();run(s,'finance','expense',{description:'Power',account:'Utilities',amount:'10',date:'2026-09-16',reference:'E1'},key);assert.throws(()=>run(s,'finance','expense',{description:'Power',account:'Utilities',amount:'20',date:'2026-09-16',reference:'E1'},key),e=>e.status===409);s.close();});
test('reservation competition cannot oversell; duplicate payment reference cannot post twice',()=>{const s=setup();const a=newOrder(s,'HC-502',4),b=newOrder(s,'HC-502',4);for(const o of [a,b]){pay(s,o.id,'100');run(s,'finance','release',{id:o.id});}run(s,'stock','reserve',{id:a.id});assert.throws(()=>run(s,'stock','reserve',{id:b.id}),/No available/);assert.equal(s.get('products','HC-502').reserved,4);const ref=randomUUID();run(s,'finance','payment',{id:a.id,amount:'1',method:'Bank',reference:ref});assert.throws(()=>run(s,'finance','payment',{id:b.id,amount:'1',method:'Bank',reference:ref}),e=>e.status===409);s.close();});
test('purchase requires approval, partial receipts cannot exceed quantity, journals balance',()=>{const s=setup();const p=run(s,'stock','purchase',{supplier:'Local supplier',productId:'HC-101',quantity:5,unitCost:'250',dueDate:'2026-10-01'});assert.throws(()=>run(s,'stock','receivePurchase',{id:p.id,quantity:5}),/approval/);run(s,'gm','approvePurchase',{id:p.id});run(s,'stock','receivePurchase',{id:p.id,quantity:2});run(s,'stock','receivePurchase',{id:p.id,quantity:3});assert.throws(()=>run(s,'stock','receivePurchase',{id:p.id,quantity:1}));run(s,'finance','paySupplier',{id:p.id,amount:'1250',reference:'SUP1'});assert.equal(s.get('purchases',p.id).paid,125000);assert.equal(report(s,s.get('employees','md')).ledger.reduce((v,l)=>v+l.debit-l.credit,0),0);s.close();});
test('source audit events are append-only and period closure rolls back the whole command',()=>{const s=setup();assert.throws(()=>s.db.exec('DELETE FROM events'),/immutable/);assert.throws(()=>s.db.exec("UPDATE events SET data='{}'"),/immutable/);run(s,'finance','periodClose',{date:'2026-09-15',reason:'Closed reviewed period'});const count=s.list('expenses').length;assert.throws(()=>run(s,'finance','expense',{description:'Late expense',account:'Rent',amount:'100',date:'2026-09-15',reference:'LATE'}),/closed/);assert.equal(s.list('expenses').length,count);s.close();});
test('daily table placement is unique per worker/date/shift and notifies that employee',()=>{const s=setup();const data={employeeId:'finishing1',centre:'Grains',date:'2026-10-01',shift:'Day'};run(s,'supervisor','assignment',data);run(s,'supervisor','assignment',{...data,centre:'Spray Paint'});assert.equal(s.list('assignments').filter(a=>a.employeeId==='finishing1'&&a.date===data.date).length,1);assert.ok(s.list('notifications').some(n=>n.userId==='finishing1'&&n.title.includes('Spray Paint')));s.close();});
test('Stock cannot overwrite financial product fields; Finance can set price and cost',()=>{const s=setup();const old=s.get('products','HC-101');run(s,'stock','product',{...old,price:'1',cost:'1',tax:'28',minimum:20});let p=s.get('products',old.id);assert.equal(p.cost,old.cost);assert.equal(p.price,old.price);assert.equal(p.taxBps,old.taxBps);run(s,'finance','product',{...p,price:'700',cost:'300',tax:'5'});p=s.get('products',old.id);assert.equal(p.price,70000);assert.equal(p.cost,30000);s.close();});
test('returns restore stock only after inspection and credit notes post once',()=>{const s=setup();const o=newOrder(s);pay(s,o.id,(o.total/100).toFixed(2));for(const [u,a]of [['finance','release'],['stock','reserve'],['stock','pack'],['finance','invoice'],['finance','clear']])run(s,u,a,{id:o.id});run(s,'stock','dispatch',{id:o.id,carrier:'Review',recipient:'Review'});const r=run(s,'stock','returnGoods',{id:o.id,lineId:o.lines[0].id,quantity:1,disposition:'RESTOCK',reason:'Inspected return'});run(s,'finance','creditNote',{id:r.id,reason:'Returned item'});assert.throws(()=>run(s,'finance','creditNote',{id:r.id,reason:'Duplicate'}),/already credited/);assert.equal(s.get('products','HC-101').onHand,33);assert.equal(report(s,s.get('employees','md')).ledger.reduce((v,l)=>v+l.debit-l.credit,0),0);s.close();});
test('data and order audit survive a database close and reopen',()=>{const path=join(mkdtempSync(join(tmpdir(),'hani-test-')),'test.sqlite');let s=openStore(path);seed(s);const o=newOrder(s);s.close();s=openStore(path);assert.equal(s.get('orders',o.id).number,o.number);assert.ok(s.events().some(e=>e.orderId===o.id));assert.equal(s.db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');s.close();});
test('real HTTP: all 23 logins, role checks, CSRF, disabled account, persistent session revocation',async()=>{const {server,store}=createApp({database:':memory:',reviewSeed:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const post=async(path,body,cookie='',extra={})=>fetch(origin+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,...extra},body:JSON.stringify(body)});try{let mdCookie,workerCookie;for(const user of store.list('employees')){const r=await post('/api/login',{email:user.email,password:REVIEW_PASSWORD});assert.equal(r.status,200,user.email);const cookie=r.headers.get('set-cookie').split(';')[0];const boot=await fetch(origin+'/api/bootstrap',{headers:{Cookie:cookie}});assert.equal(boot.status,200);assert.equal((await boot.json()).user.id,user.id);if(user.id==='md')mdCookie=cookie;if(user.id==='finishing1')workerCookie=cookie;}
 assert.equal((await fetch(origin+'/api/list?kind=journals',{headers:{Cookie:workerCookie}})).status,403);
 assert.equal((await post('/api/command',{action:'payment',data:{id:'o1',amount:'10',reference:'x',method:'Cash'}},workerCookie,{'Idempotency-Key':randomUUID()})).status,403);
 assert.equal((await post('/api/command',{action:'profile',data:{name:'Wrong origin'}},mdCookie,{'Origin':'https://attacker.invalid','Idempotency-Key':randomUUID()})).status,403);
 const w=store.get('employees','finishing1');const disabled=await post('/api/command',{action:'employee',data:{...w,active:false,password:undefined}},mdCookie,{'Idempotency-Key':randomUUID()});assert.equal(disabled.status,200);
 assert.equal((await fetch(origin+'/api/bootstrap',{headers:{Cookie:workerCookie}})).status,401);assert.equal((await post('/api/login',{email:w.email,password:REVIEW_PASSWORD})).status,401);
 const list=await fetch(origin+'/api/list?kind=employees&size=12',{headers:{Cookie:mdCookie}});const page=await list.json();assert.equal(page.rows.length,12);assert.ok(page.next);assert.ok(page.rows.every(u=>!u.passwordHash));const page2=await fetch(origin+'/api/list?kind=employees&size=12&cursor='+page.next,{headers:{Cookie:mdCookie}});assert.equal((await page2.json()).rows.length,11);
 }finally{await new Promise(r=>server.close(r));store.close();}});
